#!/usr/bin/env python3
"""Render Axiom papers and publish them into the site's public assets.

One Quarto source per paper produces two published outputs:

  public/papers/<slug>/web/        the self-contained HTML the site embeds
  public/papers/<slug>/<slug>.pdf  the download, and what goes to a preprint server

Both are committed, because Vercel builds the site without Quarto installed —
the renders are inputs to the deploy, not products of it. Re-run this after
editing a manuscript or the theme, and commit what changes.

    python3 papers/render.py                # every paper
    python3 papers/render.py conformance    # one paper

The design-system's custom properties are extracted into papers/theme/tokens.css
before each render, so a manuscript cannot drift from the site's palette: there
is one source of colour and the paper reads it.
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PAPERS_DIR = ROOT / "papers"
THEME_DIR = PAPERS_DIR / "theme"
PUBLIC_DIR = ROOT / "public" / "papers"

# Prefer the built package (what the site actually ships) and fall back to the
# source token file so a clean checkout can render without a bun install.
TOKEN_CANDIDATES = (
    ROOT / "packages" / "ui" / "dist" / "styles" / "tokens.css",
    ROOT / "packages" / "ui" / "src" / "styles" / "tokens.css",
)


def find_quarto() -> str:
    found = shutil.which("quarto")
    if found:
        return found
    # Quarto's default user install location on macOS.
    fallback = Path.home() / ".local" / "bin" / "quarto"
    if fallback.exists():
        return str(fallback)
    sys.exit(
        "quarto not found. Install it from https://quarto.org/docs/get-started/ "
        "and re-run."
    )


def sync_tokens() -> Path:
    """Extract the design-system custom properties into plain CSS for the paper.

    The site's token file declares its variables inside Tailwind's `@theme`
    at-rule. Tailwind compiles that away at build time, but the manuscript is
    rendered by Quarto and read by a browser directly — and a browser ignores
    `@theme` wholesale, so every `var(--color-…)` in the paper silently falls
    back to nothing. (That failure is invisible in the HTML: it renders, just
    unstyled.)

    So rather than copying the file, lift its `--*` declarations into a plain
    `:root` block. Values still come from one place; only the syntax changes.
    """
    source = next((path for path in TOKEN_CANDIDATES if path.exists()), None)
    if source is None:
        sys.exit(
            "No design-system tokens found. Run `bun run build:ui` first, or "
            f"check {TOKEN_CANDIDATES[0].relative_to(ROOT)}."
        )

    declarations = re.findall(
        r"^\s*(--[A-Za-z0-9-]+)\s*:\s*([^;]+);",
        source.read_text(),
        flags=re.MULTILINE,
    )
    if not declarations:
        sys.exit(f"No custom properties found in {source.relative_to(ROOT)}.")

    # Later declarations win in CSS, and the source file may legitimately
    # redeclare a property; keep the last value for each name, in first-seen
    # order so the output stays readable and diffable.
    values: dict[str, str] = {}
    for name, value in declarations:
        values[name] = value.strip()

    body = "\n".join(f"  {name}: {value};" for name, value in values.items())
    destination = THEME_DIR / "tokens.css"
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(
        "/* GENERATED by papers/render.py from "
        f"{source.relative_to(ROOT)} — do not edit.\n"
        " * The design system declares these inside Tailwind's @theme, which a\n"
        " * browser ignores; the manuscript needs them as plain custom\n"
        " * properties. Edit the source file, then re-render.\n"
        " */\n"
        ":root {\n"
        "  /* The palette is light-only, so say so: a dark-mode browser would\n"
        "     otherwise paint its own scrollbars and form controls dark against\n"
        "     it. */\n"
        "  color-scheme: light;\n"
        f"{body}\n"
        "}\n"
    )
    print(f"  {len(values)} custom properties extracted")
    return destination


def discover(slug: str | None) -> list[Path]:
    if slug:
        directory = PAPERS_DIR / slug
        if not (directory / "_quarto.yml").exists():
            sys.exit(f"No paper at papers/{slug} (expected a _quarto.yml there).")
        return [directory]
    return sorted(
        path.parent
        for path in PAPERS_DIR.glob("*/_quarto.yml")
    )


def render(paper: Path, quarto: str) -> None:
    slug = paper.name
    print(f"→ {slug}")

    # `quarto render` on a manuscript project emits every declared format.
    subprocess.run([quarto, "render"], cwd=paper, check=True)

    out = paper / "out"
    if not out.exists():
        sys.exit(f"{slug}: quarto produced no out/ directory.")

    public = PUBLIC_DIR / slug
    web = public / "web"
    if web.exists():
        shutil.rmtree(web)
    web.mkdir(parents=True, exist_ok=True)

    # `embed-resources` inlines every stylesheet and script, so the article
    # HTML is the whole web render. Quarto still writes its asset bundle and a
    # LaTeX intermediate tree next to it; publishing those would ship ~140KB of
    # files nothing loads, so copy only the document.
    article = out / "index.html"
    if not article.exists():
        sys.exit(f"{slug}: expected {article.relative_to(ROOT)} after render.")
    shutil.copy2(article, web / "index.html")

    # Quarto names the PDF after the source document. Publish it under the
    # paper's slug so the download has a meaningful filename.
    pdfs = list(out.glob("*.pdf"))
    if pdfs:
        shutil.copy2(pdfs[0], public / f"{slug}.pdf")
        print(f"  pdf  public/papers/{slug}/{slug}.pdf")
    else:
        print(f"  !! {slug}: no PDF produced — check the LaTeX log above.")

    print(f"  web  public/papers/{slug}/web/index.html")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("slug", nargs="?", help="Render only this paper.")
    args = parser.parse_args()

    quarto = find_quarto()
    tokens = sync_tokens()
    print(f"tokens ← {tokens.relative_to(ROOT)}")

    papers = discover(args.slug)
    if not papers:
        sys.exit("No papers found under papers/.")

    for paper in papers:
        render(paper, quarto)

    print("\nDone. Preview at /papers once the dev server reloads.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
